### PR TITLE
Add P prefix on persistence related classes

### PR DESCRIPTION
**Pull request by lakhina**

### CODE REVIEW

**Comment by TimMoore** [comment]
I'd like to hold off on this until a decision is made on #98.

**Comment by ignasi35** [comment]
let's merge now and rename later at once.

**Comment by lakhina** [comment]
@TimMoore @ignasi35 Both ways looks good to me. As per you guys decide

**Comment by TimMoore** [comment]
OK I'll merge now to keep this from staying open and blocking other changes.

**Pull request merged**
