### PR TITLE
[WIP] Prepares online-auction to Lagom 1.4.0 bump

### PR DESCRIPTION
**Pull request by ignasi35**
This currently requires a local compilation of the https://github.com/lagom/lagom/tree/play-2.6-akka-2.5 branch.

### CODE REVIEW

**Comment by ignasi35** [comment]
This currently has some issue on the play app: `webGateway`

**Comment by ignasi35** [comment]
> This currently has some issue on the play app: webGateway

The issues are now solved (see 85dce88) but there's still work to be done:

- [ ] use new play default filters (play25 had XSS, CSRF,... disabled by default and play26 adds them by default). I'd be good to have the filters enabled
- [ ] test this over an environment where there's data created with an `online-auction-java` running on Lagom 13x. That would help detect issues for users upgrading a production environment.

**Comment by TimMoore** [comment]
@ignasi35 is it possible to rework this in a way that it is compatible with _both_ Lagom 1.3 and 1.4?

That way, we could merge everything but the version bump, rather than leaving this open as a long-lived branch.

We can then fix new deprecations in a subsequent PR, once Lagom 1.4 is released.

**Comment by ignasi35** [comment]
> @ignasi35 is it possible to rework this in a way that it is compatible with both Lagom 1.3 and 1.4?

It will need some thought. I'm not 100% familiar with all the changes and I think at least the form validation is not compatible.

We can consider this branch as a playground to smoke test and prevent further surprises.

**Comment by renatocaval** [comment]
done by #164

**Comment by renatocaval** [comment]
Done by #164

**Pull request closed without merging**
