### PR TITLE
Fixes #31 Add i18n values for validation error keys

### LINKED ISSUE #31: Missing i18n values for validation error keys
The web frontend is missing i18n keys for some validation errors, such as invalid.step.

### PR DESCRIPTION
**Pull request by lakhina**
lagom#31

### CODE REVIEW

**Comment by ignasi35** [comment]
Hi @lakhina I'm confused by you second comment:

> [WIP] lagom#31

is this PR ready for merge or are you still working on it?

So far it looks great, btw! ;-)

**Comment by ignasi35** [comment]
Hi @lakhina , I have two final request:
 * would you please rename the PR so that it's not such a generic title?
 * when a PR is a addressing an issue, a reference to the issue like to added in the description is great so there's traceability. If you use the sentence "Fixes #issueNumber" it's event better as GitHub will update the issue automatically when the PR is merged.

**Comment by lakhina** [comment]
@ignasi35  Work is complete now from my side and ready for review and merge. And thanks for pointers on PR name. I am new to GitHub will take care in future

**Comment by ignasi35** [comment]
Hi @lakhina, we've all been "new to github" at one point. ;-)

The new PR title is great as it captures the intent of the work done.
Regarding "Fixes #31", my previous comment was ambiguous and that's meant to be in a comment (not the title). You'll get the gist of it, don't worry about this PR now as I'm merging it.

**Pull request merged**
