### PR TITLE
Remove custom optional serializer

### LINKED ISSUE #75: Remove custom optional serializer
#11 introduced a custom serializer for java Optional (see https://github.com/lagom/online-auction-java/blob/master/item-impl/src/main/resources/application.conf#L11-L19 and related class/es).

When this is provided by Akka the custom serializer should be removed and the provided by used instead.

### PR DESCRIPTION
**Pull request by lakhina**
fix #75 by using `akka.remote.serialization.MiscMessageSerializer` instead of custom optional serializer.

### CODE REVIEW

**Comment by lakhina** [comment]
@ignasi35 Can you please confirm I am moving right way?

**Comment by ignasi35** [comment]
HI @lakhina I don't think we need any serializer. If this app is using the latest lagom, the optional serializer should be picked up, doesn't it?
I haven't looked into it in a while so I trust your tests. Does it fail without `MiscMessageSerializer ` ?

**Comment by lakhina** [comment]
@ignasi35 I haven't tested without `MiscMessageSerializer` but i took reference from https://github.com/akka/akka/blob/master/akka-remote/src/main/resources/reference.conf#L51

**Comment by lakhina** [comment]
I felt if akka is using it then there should be a need for it.

**Comment by lakhina** [comment]
@ignasi35  Thanks. It is working good without `MiscMessageSerializer`

**Comment by ignasi35** [comment]
Good job!

**Pull request merged**
